### ISSUE TITLE
Missing boundary check (overflow)

### ISSUE THREAD

**Issue by peppergrayxyz** [mauro-balades/ultimate-string-library#1]
Hi,

saw your post in r/C_Programming, looks like a nice project :D

I browsed through your code and I think there is an issue with memory management due to missing boundary checks:
- ```usl_new``` should check if ```size``` is less than the maximum 4 bytes (```USL_SIZE```)
- ```usl_from``` should check if ```len``` is less than the maximum 4 bytes (```USL_SIZE```)
- ```usl_concat``` should check if ```new_len``` is less than the maximum 4 bytes (```USL_SIZE```)

**Comment by mauro-balades** [comment]
https://github.com/mauro-balades/ultimate-string-library/commit/470a995553508fef3cdb7507528a1f01f35ffa2a
